name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source du dépôt
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: pip install -r flask-ci-cd/api/requirements.txt

      - name: Exécution des tests
        run: pytest api/

      - name: Message de succès
        run: echo "Tous les tests sont passés avec succès !"

  build:
    name: build
    runs-on: ubuntu-latest
    needs: pytest

    steps:
      - name: Récupération du code source du dépôt
        uses: actions/checkout@v3

      - name: Construction de l'image Docker
        run: docker build -t flask-api api/